' Gambas module file

' Gambas module file


PUBLIC SUB leer(rejilla AS gridview, titulos AS Boolean) 

'rejilla: es el gridview donde se van a escribir los datos
'titulos: 0: sin titulo, -1 titulo contiene la 1º fila


DIM lineas AS String[]
DIM linea_procesada AS String
DIM columnas AS String[]
DIM a AS Integer
DIM c AS Integer
DIM cadena AS String
DIM portapapeles AS String
DIM finlinea AS String
DIM fincolumna AS String
DIM info AS Integer
DIM categoria AS String
DIM deli AS String
DIM aplicacion AS String
DIM ejecutar AS String
DIM punto AS String
DIM icono AS String

deli = " = "
finlinea = "\n" ' retorno de carro (separa las filas)
fincolumna = "\t" 'tabulador (separa las colunas)



SHELL "cat /usr/share/applications/*.desktop | grep ^Name= | cut -d" & deli & " -f2 | sort" TO portapapeles

lineas = Split(portapapeles, finlinea)




FOR a = 0 TO lineas.count - 1
linea_procesada = lineas[a]

columnas = Split(linea_procesada, fincolumna)



FOR c = 0 TO columnas.count - 1
IF a = 0 AND titulos = -1 THEN 
rejilla.Columns[c].title = columnas[c]

ELSE

IF titulos = 0 THEN rejilla[a, c].text = columnas[c]
IF titulos = -1 THEN rejilla[a - 1, c].text = columnas[c]
ENDIF 

NEXT 'c


NEXT 'a


  
END

